import { Container } from "@chakra-ui/react";
import Head from "next/head";
import { ReactNode } from "react";
import Alert from "./index/Alert";

interface LayoutProps {
  title?: string;
  description?: string;
  children: ReactNode;
}

export default function Layout({
  children,
  title = "default title",
  description = "default description",
}: LayoutProps) {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Alert />
      <Container p={0} bg="blue.100" minH="100vh" minW="full">
        {children}
      </Container>
    </>
  );
}
